### ISSUE TITLE
BoundingBox format in CustomDataset

### ISSUE THREAD

**Issue by torleivf** [ZJULearning/ttfnet#13]
Hi, I was reading through ttfnet/mmdet/datasets/custom.py and https://github.com/ZJULearning/ttfnet/blob/master/GETTING_STARTED.md, as I will train TTFNet with a custom dataset. The getting started page is very helpful.

The question is what format one should use for the bboxes;
(X_TopLeft, Y_TopLeft, X_BottomRight, Y_BottomRight)  
or
(X_TopLeft, Y_TopLeft, Width, Height)

Clarification would be greatly appreciated.

**Comment by liuzili97** [comment]
Hi, it should be the first one (X_TopLeft, Y_TopLeft, X_BottomRight, Y_BottomRight).

**Comment by torleivf** [comment]
Thank you
