### ISSUE TITLE
question about 'wh_offset_base'

### ISSUE THREAD

**Issue by xieenze** [ZJULearning/ttfnet#17]
Hi, thanks for your great work.
I am confused that 'wh_offset_base' =16 in ttf_head.py,  but I don't know why you need to set this parameter.  
![image](https://user-images.githubusercontent.com/20984575/70307026-33411480-1843-11ea-8187-e4b2b9bcbe45.png)

Why do you need to multiply it in the regression head?  Thanks.

**Comment by liuzili97** [comment]
Hi. We use it to enlarge the prediction since directly predicting large values is hard. After using this parameter, we just need to predict the 1/16 of the values, which can be easier.

**Comment by xieenze** [comment]
@liuzili97 Thanks for quick reply.
But the thing is that I do not find you use this parameter during inference. I think  'wh_offset_base' should also be used during inference. =-=

**Comment by liuzili97** [comment]
This parameter is used in both training and inference since the `forward` will be called anyway.

**Comment by xieenze** [comment]
Thanks. I get it.
