### ISSUE TITLE
用了可行变卷积，但是论文没说

### ISSUE THREAD

**Issue by luuuyi** [ZJULearning/ttfnet#31]
作者你好，代码里面我看到你们用了DCN，这个肯定对最终性能帮助很大，但是论文里面我没看到有提到这个地方，不知道是不是我疏忽了，你们有对比不用DCN只采用普通卷积的性能么。

**Comment by JoJoliking** [comment]
@luuuyi The paper has mentioned in page 5, Over all design. You can see that there is MDCN in this part

**Comment by luuuyi** [comment]
@JoJoliking thank you for your reply.
